apiVersion: v1
kind: Pod
metadata:
  name: working-pod3-15
spec:
  containers:
    - name: new-container
      env:
       - name: PASSWDFILE
         value: "/root/tconfig-file.conf"
      image: nlingareddy/ssh-login-node
      volumeMounts:
        - name: config-vol
          mountPath:  /root/tconfig-file.conf
          subPath: tconfig-file.conf  
      command: ["/bin/sh", "-c"]
      args:
        -  echo $PASSWDFILE >> pass.conf;
           vi pass.conf +w +q;
           ./config/init/new.sh pass.conf;
           tail -f /dev/null; 
  volumes:
    - name: config-vol 
      configMap: 
        name: new2-config
        items: 
         - key: tconfig-file.conf
           path: tconfig-file.conf
